import MypageNav from "@/components/layout/my/MypageNav";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <>
          <div style={{ width : "80%", height : "100%",marginTop : "50px"}}>
            <MypageNav/>
            <div style={{height : "100%", width : "100%", paddingLeft: "200px"}}>
              {children}
            </div>
          
          </div>
        </>
    );
  }
  