import MypageNav from "@/components/layout/my/MypageNav";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <>
          <MypageNav/>
          <div style={{marginInline: "10vw", paddingLeft : "200px", height : "100%",  paddingTop: "50px"}}>
            {children}
          </div>
        </>
    );
  }
  